import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Cloud File Manager",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
    session,
}: Readonly<{
    children: React.ReactNode;
    session: Session;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session}>
                    <div className="flex">
                        <Sidebar />
                        <div className="grid grid-cols-1 md:grid-cols-3 w-full">
                            <div className="col-span-2">{children}</div>
                            <div className="bg-white p-4">Storage</div>
                        </div>
                    </div>
                </SessionProvider>
            </body>
        </html>
    );
}
